jobscript: "float-jobscript.sh"
cluster: "float_submit.py"
cluster-status: "float_status.py"
cluster-cancel: "float_cancel.py"
no-shared-fs: true
drop-metadata: true
rerun-incomplete: true
output-wait: 60